# Generated by Django 5.2.5 on 2025-09-03 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.CharField(max_length=150)),
                ('artiste', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.CharField(max_length=150)),
                ('realisateur', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('createur', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
