# Generated by Django 5.2.5 on 2025-11-07 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mediatheque_project.emprunteur'),
        ),
    ]
