# Generated by Django 5.2.5 on 2026-02-24 12:04

import app_bibliothecaire.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(blank=True, null=True)),
                ('dateRetour', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.CharField(max_length=150)),
                ('artiste', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(blank=True, null=True)),
                ('dateRetour', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.CharField(max_length=150)),
                ('realisateur', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('createur', models.CharField(max_length=150)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(blank=True, null=True)),
                ('dateRetour', models.DateTimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('emprunteur', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMedia', models.CharField(choices=[('livre', 'Livre'), ('dvd', 'DVD'), ('cd', 'CD')], max_length=10)),
                ('idMedia', models.IntegerField()),
                ('dateEmprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateRetour', models.DateTimeField(default=app_bibliothecaire.models.dateRetourDefaut)),
                ('mediaRendu', models.BooleanField(default=False)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_bibliothecaire.emprunteur')),
            ],
        ),
    ]
